class AppTexts {
  static final Map<String, Map<String, String>> data = {
    'ru': {
      // Общие
      'ru': 'Русский',
      'kg': 'Кыргызча',
      'save': 'Сохранить',
      'edit': 'Изменить',
      'goal': 'Моя цель',
      'progress': 'Прогресс',
      'advice': 'Совет',
      'forecast': 'Прогноз',
      'score': 'Финансовая оценка',
      'settings': 'Настройки',
      'language': 'Язык',

      // Main
      'home_title': 'Главная',
      'subtitle': 'Заботимся о ваших финансах',
      'goal_dream': 'Накопить на мечту ✨',
      'goal_saved_text': 'Накоплено 50 000 сом из 100 000 сом',
      'income': 'Доход',
      'expense': 'Расход',
      'saved': 'Сэкономлено',
      'great_job': 'Отличная работа!',
      'last_operations': 'Последние операции',
      'all_operations': 'Все операции',
      'salary': 'Зарплата',
      'income_arrival': 'Поступление',
      'supermarket': 'Супермаркет',
      'products': 'Продукты',
      'coffee_shop': 'Кофейня',
      'cafes_restaurants': 'Кафе и рестораны',
      'today': 'Сегодня',
      'yesterday': 'Вчера',
      'ai_title': 'Анализ ИИ',
      'ai_desc': 'Получите персональные советы и анализ ваших финансов',
      'ai_button': 'Посмотреть анализ',

      // Profile
      'profile': 'Профиль',
      'profile_subtitle': 'Твой финансовый путь начинается здесь',
      'edit_profile': 'Редактировать профиль',
      'personal_info': 'Личная информация',
      'name': 'Имя',
      'email': 'Email',
      'phone': 'Телефон',
      'my_finances': 'Мои финансы',
      'current_goal': 'Текущая цель',
      'saved_amount': 'Накоплено',
      'notifications': 'Уведомления',
      'enabled': 'Включены',
      'security': 'Безопасность',
      'pin_code': 'PIN-код',

      // Edit profile
      'edit_profile_screen': 'Редактировать профиль',

      // Finance details
      'finance': 'Финансы',
      'finance_details_subtitle': 'Подробная информация по операциям',
      'total_balance': 'Общий баланс',
      'income_more_than_expense': 'Доходы больше расходов — это хороший результат',
      'incomes': 'Доходы',
      'expenses': 'Расходы',
      'main_income': 'Основной доход',
      'side_job': 'Подработка',
      'additional_income': 'Дополнительный доход',
      'transport': 'Транспорт',
      'road_and_trips': 'Дорога и поездки',
      'results_and_tips': 'Итоги и советы',
      'daily_expenses_tip': 'Можно сократить мелкие ежедневные траты',
      'goal_left_text': 'До цели осталось 94 900 сом',
      'view_full_analysis': 'Посмотреть полный анализ',

      // AI analysis
      'ai_month_notice': 'Вот что мы заметили за этот месяц',
      'financial_result': 'Финансовый итог',
      'saved_this_month': 'Ты сохранил в этом месяце',
      'main_insight': 'Главный инсайт',
      'main_insight_text':
          'Больше всего денег ушло на еду, кафе и ежедневные мелкие покупки.',
      'ai_advice': 'Совет ИИ',
      'ai_advice_text_short':
          'Если сократить спонтанные траты хотя бы на 15%, ты сможешь сохранять ещё 3 000 сом в месяц.',
      'ai_forecast_text':
          'Если продолжишь так же, ты сможешь накопить 100 000 сом примерно за 5 месяцев.',
      'what_to_improve': 'Что можно улучшить',
      'improve_tip_1': 'Снизить траты на кофе и перекусы',
      'improve_tip_2': 'Поставить недельный лимит расходов',
      'improve_tip_3': 'Откладывать фиксированную сумму сразу после поступления',
      'create_savings_plan': 'Создать план накопления',

      // Full analysis
      'analysis': 'Полный анализ',
      'analysis_subtitle': 'ИИ-разбор твоих финансов за месяц',
      'month_result': 'Итог месяца',
      'month_result_desc': 'Столько осталось после всех расходов',
      'saved_short': 'Сохранил',
      'where_money_went': 'Куда ушли деньги',
      'cafes': 'Кафе',
      'budget_drains': 'Что тянет бюджет вниз',
      'problem_category': 'Проблемная категория',
      'problem_category_text':
          'Больше всего лишних трат сейчас уходит на кафе, перекусы и мелкие ежедневные покупки.',
      'repeating_expenses': 'Повторяющиеся расходы',
      'repeating_expenses_text':
          'За месяц было много мелких одинаковых трат. Они кажутся незаметными, но в сумме сильно уменьшают остаток денег.',
      'advice_text':
          'Если сократить спонтанные траты хотя бы на 15%, ты сможешь сохранять ещё примерно 2 000–3 000 сом в месяц.',
      'after_1_month': 'Через 1 месяц',
      'after_3_months': 'Через 3 месяца',
      'after_6_months': 'Через 6 месяцев',
      'financial_discipline': 'Финансовая дисциплина',
      'financial_discipline_text':
          'Хороший уровень. Но можно ещё улучшить контроль мелких расходов.',
      'improvement_plan': 'План улучшения',
      'plan_item_1': 'Установить лимит на кафе: 1 500 сом',
      'plan_item_2': 'Снизить мелкие ежедневные траты',
      'plan_item_3': 'Откладывать деньги сразу после поступления',
      'create_financial_plan': 'Создать личный финансовый план',
    },

    'kg': {
      // Общие
      'ru': 'Орусча',
      'kg': 'Кыргызча',
      'save': 'Сактоо',
      'edit': 'Өзгөртүү',
      'goal': 'Менин максатым',
      'progress': 'Жүрүш',
      'advice': 'Кеңеш',
      'forecast': 'Божомол',
      'score': 'Каржылык баа',
      'settings': 'Жөндөөлөр',
      'language': 'Тил',

      // Main
      'home_title': 'Башкы',
      'subtitle': 'Каржыларыңызга кам көрөбүз',
      'goal_dream': 'Кыялга акча топтоо ✨',
      'goal_saved_text': '50 000 сом топтолду, 100 000 сомдун ичинен',
      'income': 'Киреше',
      'expense': 'Чыгым',
      'saved': 'Үнөмдөлдү',
      'great_job': 'Абдан жакшы!',
      'last_operations': 'Акыркы операциялар',
      'all_operations': 'Бардык операциялар',
      'salary': 'Айлык',
      'income_arrival': 'Түшүү',
      'supermarket': 'Супермаркет',
      'products': 'Азык-түлүк',
      'coffee_shop': 'Кофейня',
      'cafes_restaurants': 'Кафе жана ресторандар',
      'today': 'Бүгүн',
      'yesterday': 'Кечээ',
      'ai_title': 'ЖИ анализ',
      'ai_desc': 'Каржыңыз боюнча жеке кеңештерди жана анализди алыңыз',
      'ai_button': 'Анализди көрүү',

      // Profile
      'profile': 'Профиль',
      'profile_subtitle': 'Сиздин каржылык жолуңуз ушул жерден башталат',
      'edit_profile': 'Профилди өзгөртүү',
      'personal_info': 'Жеке маалымат',
      'name': 'Аты',
      'email': 'Email',
      'phone': 'Телефон',
      'my_finances': 'Менин каржым',
      'current_goal': 'Учурдагы максат',
      'saved_amount': 'Топтолгон сумма',
      'notifications': 'Эскертмелер',
      'enabled': 'Күйгүзүлгөн',
      'security': 'Коопсуздук',
      'pin_code': 'PIN-код',

      // Edit profile
      'edit_profile_screen': 'Профилди өзгөртүү',

      // Finance details
      'finance': 'Каржы',
      'finance_details_subtitle': 'Операциялар боюнча толук маалымат',
      'total_balance': 'Жалпы баланс',
      'income_more_than_expense': 'Киреше чыгымдан көп — бул жакшы жыйынтык',
      'incomes': 'Кирешелер',
      'expenses': 'Чыгымдар',
      'main_income': 'Негизги киреше',
      'side_job': 'Кошумча иш',
      'additional_income': 'Кошумча киреше',
      'transport': 'Унаа',
      'road_and_trips': 'Жол жана сапарлар',
      'results_and_tips': 'Жыйынтык жана кеңештер',
      'daily_expenses_tip': 'Күнүмдүк майда чыгымдарды азайтууга болот',
      'goal_left_text': 'Максатка жетиш үчүн дагы 94 900 сом керек',
      'view_full_analysis': 'Толук анализди көрүү',

      // AI analysis
      'ai_month_notice': 'Бул айда биз төмөнкүлөрдү байкадык',
      'financial_result': 'Каржылык жыйынтык',
      'saved_this_month': 'Сиз бул айда үнөмдөдүңүз',
      'main_insight': 'Негизги байкоо',
      'main_insight_text':
          'Акчанын көбү тамак-ашка, кафеге жана күнүмдүк майда сатып алууларга кеткен.',
      'ai_advice': 'ЖИ кеңеши',
      'ai_advice_text_short':
          'Эгер күтүүсүз чыгымдарды 15%га азайтсаңыз, айына дагы 3 000 сом үнөмдөй аласыз.',
      'ai_forecast_text':
          'Ушундай улантсаңыз, 100 000 сомду болжол менен 5 айда топтой аласыз.',
      'what_to_improve': 'Эмнени жакшыртууга болот',
      'improve_tip_1': 'Кофе жана жеңил тамактарга кеткен чыгымды азайтуу',
      'improve_tip_2': 'Жумалык чыгым лимитин коюу',
      'improve_tip_3': 'Акча түшөр замат белгилүү сумманы бөлүп коюу',
      'create_savings_plan': 'Топтоо планын түзүү',

      // Full analysis
      'analysis': 'Толук анализ',
      'analysis_subtitle': 'Бир айлык каржыңыз боюнча ЖИ талдоосу',
      'month_result': 'Айдын жыйынтыгы',
      'month_result_desc': 'Бардык чыгымдардан кийин ушунча калды',
      'saved_short': 'Топтолду',
      'where_money_went': 'Акча кайда кетти',
      'cafes': 'Кафелер',
      'budget_drains': 'Бюджетти эмне азайтып жатат',
      'problem_category': 'Көйгөйлүү категория',
      'problem_category_text':
          'Кошумча чыгымдардын көбү кафе, жеңил тамак жана күнүмдүк майда сатып алууларга кетип жатат.',
      'repeating_expenses': 'Кайталанган чыгымдар',
      'repeating_expenses_text':
          'Ай ичинде көп майда кайталанган чыгымдар болду. Алар байкалбайт, бирок жыйынтыгында каражатты азайтат.',
      'advice_text':
          'Эгер күтүүсүз чыгымдарды 15%га азайтсаңыз, айына дагы болжол менен 2 000–3 000 сом үнөмдөй аласыз.',
      'after_1_month': '1 айдан кийин',
      'after_3_months': '3 айдан кийин',
      'after_6_months': '6 айдан кийин',
      'financial_discipline': 'Каржылык тартип',
      'financial_discipline_text':
          'Жакшы деңгээл. Бирок майда чыгымдарды көзөмөлдөөнү дагы жакшыртса болот.',
      'improvement_plan': 'Жакшыртуу планы',
      'plan_item_1': 'Кафеге лимит коюу: 1 500 сом',
      'plan_item_2': 'Күнүмдүк майда чыгымдарды азайтуу',
      'plan_item_3': 'Акча түшөрү менен дароо бөлүп коюу',
      'create_financial_plan': 'Жеке каржылык план түзүү',
      'history': 'История',
      'history': 'Тарых',
      'last_operations': 'Последние операции',
       'all_operations': 'Все операции',
       'today': 'Сегодня',
       'yesterday': 'Вчера',
        'salary': 'Зарплата',
       'income_arrival': 'Поступление',
       'supermarket': 'Супермаркет',
       'coffee_shop': 'Кофейня',
       'cafes_restaurants': 'Кафе и рестораны',
    },
  };

  static String get(String lang, String key) {
    return data[lang]?[key] ?? key;
  }
}